// Persistencia local versionada. El contenido ingresado siempre se escapa al mostrarlo.
window.QuestionStore=(()=>{
 const key='biblodera.questions.v1';let error='';
 const empty=()=>({version:1,seconds:15,questions:[]});
 function validate(v){
  if(!v||v.version!==1||!Number.isInteger(v.seconds)||v.seconds<5||v.seconds>120||!Array.isArray(v.questions)||v.questions.length>500)throw Error('Usá una copia válida exportada desde La Bibliodera.');
  const ids=new Set();v.questions.forEach(q=>{
   if(!q||typeof q.id!=='string'||ids.has(q.id)||!Number.isInteger(q.category)||!BiblioderaContent.categories[q.category]||typeof q.text!=='string'||!q.text.trim()||q.text.length>160||!Array.isArray(q.options)||q.options.length!==4||q.options.some(o=>typeof o!=='string'||!o.trim()||o.length>70)||!Number.isInteger(q.correct)||q.correct<0||q.correct>3)throw Error('Hay una pregunta inválida en el archivo.');
   ids.add(q.id);
  });return v;
 }
 let value=empty();try{const saved=localStorage.getItem(key);if(saved)value=validate(JSON.parse(saved));}catch(e){error='No se pudo recuperar el banco guardado. Importá un respaldo o guardá un nuevo banco.';}
 return {get:()=>structuredClone(value),error:()=>error,validate,save(next){validate(next);try{localStorage.setItem(key,JSON.stringify(next));}catch(e){throw Error('No se pudo guardar. Revisá el espacio disponible en el equipo.');}value=structuredClone(next);error='';}};
})();
window.SettingsUI=(()=>{
 const esc=BiblioderaUI.escape;let editing=null;
 function render(stage,selected='menu'){
  if(selected==='menu'){VideoLoop.menu(stage);stage.focus({preventScroll:true});window.scrollTo(0,0);return;}
  editing=null;const state=QuestionStore.get();
  stage.innerHTML=`<section class="settings"><div class="settings-heading"><div><h1>Configuración</h1><p>Cargá las preguntas y dejá todo listo para jugar.</p></div>${BiblioderaUI.backToGame()}</div><p class="storage-note">Guardá una copia de tus preguntas para recuperarlas o usarlas en otro equipo. Entrar a Configuración termina la ronda actual.</p><p id="settings-status" role="status">${esc(QuestionStore.error())}</p>
  <div class="settings-layout"><form id="question-form"><h2 id="form-title">Nueva pregunta</h2><label>Categoría<select name="category" required>${BiblioderaContent.categories.slice(0,4).map((c,i)=>`<option value="${i}">${esc(c.label)}</option>`).join('')}</select></label><label>Pregunta<textarea name="question" rows="2" maxlength="160" required placeholder="Escribí la pregunta (hasta 160 caracteres)"></textarea></label><div class="option-fields">${'ABCD'.split('').map((l,i)=>`<label>Respuesta ${l}<input name="option${i}" maxlength="70" required placeholder="Opción ${l}"></label>`).join('')}</div><label>Respuesta correcta<select name="correct">${'ABCD'.split('').map((l,i)=>`<option value="${i}">Opción ${l}</option>`).join('')}</select></label><label>Tiempo de respuesta (segundos)<input name="seconds" type="number" min="5" max="120" step="1" value="${state.seconds}" required><small>Se aplica a todas las preguntas.</small></label><div class="form-actions"><button class="button" type="submit">Guardar pregunta y tiempo</button><button class="back-to-game" type="button" id="clear-form"><span class="back-to-game-icon" aria-hidden="true"><svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10h11a6 6 0 0 1 0 12M3 10l6-6m-6 6 6 6"/></svg></span><span>Cancelar edición</span></button></div></form>
  <div class="bank"><h2>Preguntas <span id="question-count"></span></h2><div id="question-list"></div><div class="backup-actions"><button class="quiet" id="export-bank">Exportar copia</button><label class="quiet import-label">Importar copia<input id="import-bank" type="file" accept=".json,application/json"></label></div><p class="storage-note">La importación reemplaza el banco actual después de tu confirmación. Participan las categorías con preguntas cargadas y los dos casilleros especiales. Las preguntas antiguas asignadas a esos casilleros se conservan, pero debés reasignarlas para usarlas.</p></div></div>
  <dialog id="confirm-dialog"><h2 id="confirm-title"></h2><p id="confirm-text"></p><div class="form-actions"><button class="quiet" id="confirm-cancel">Cancelar</button><button class="button" id="confirm-ok">Confirmar</button></div></dialog></section>`;
  const form=stage.querySelector('#question-form'),status=stage.querySelector('#settings-status');
  const message=text=>{status.textContent=text;};
  function reset(){editing=null;form.reset();form.elements.seconds.value=QuestionStore.get().seconds;stage.querySelector('#form-title').textContent='Nueva pregunta';}
  function save(next,text){try{QuestionStore.save(next);message(text);return true;}catch(e){message(e.message);return false;}}
  function confirm(title,text,action){const d=stage.querySelector('#confirm-dialog');d.querySelector('#confirm-title').textContent=title;d.querySelector('#confirm-text').textContent=text;d.querySelector('#confirm-cancel').onclick=()=>d.close();d.querySelector('#confirm-ok').onclick=()=>{d.close();action();};d.showModal();d.querySelector('#confirm-cancel').focus();}
  function list(){const bank=QuestionStore.get().questions;stage.querySelector('#question-count').textContent=`(${bank.length})`;stage.querySelector('#question-list').innerHTML=bank.length?bank.map(q=>`<article class="bank-item"><span>${esc(BiblioderaContent.categories[q.category].label)}</span><h3>${esc(q.text)}</h3><p>Correcta: ${'ABCD'[q.correct]} · ${esc(q.options[q.correct])}</p><div><button class="quiet" data-edit="${esc(q.id)}">Editar</button><button class="quiet" data-delete="${esc(q.id)}">Eliminar</button></div></article>`).join(''):'<div class="empty-bank"><h3>Todavía no hay preguntas</h3><p>Agregá la primera con cuatro opciones y una respuesta correcta.</p></div>';}
  form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),next=QuestionStore.get();next.seconds=Number(f.get('seconds'));const q={id:editing||crypto.randomUUID(),category:Number(f.get('category')),text:f.get('question').trim(),options:[0,1,2,3].map(i=>f.get('option'+i).trim()),correct:Number(f.get('correct'))};if(!q.text||q.options.some(o=>!o)){message('Completá la pregunta y las cuatro respuestas.');return;}if(new Set(q.options.map(o=>o.toLocaleLowerCase())).size!==4){message('Las cuatro respuestas deben ser diferentes.');return;}if(editing)next.questions=next.questions.map(x=>x.id===editing?q:x);else next.questions.push(q);if(save(next,'Pregunta y tiempo guardados.')){reset();list();}};
  stage.querySelector('#clear-form').onclick=reset;
  stage.querySelector('#question-list').onclick=e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const q=QuestionStore.get().questions.find(q=>q.id===edit.dataset.edit);editing=q.id;form.elements.category.value=q.category<4?q.category:'';if(q.category>=4)message('Esta pregunta quedó en un casillero especial. Elegí una de las cuatro categorías para que vuelva a participar.');form.elements.question.value=q.text;q.options.forEach((o,i)=>form.elements['option'+i].value=o);form.elements.correct.value=q.correct;stage.querySelector('#form-title').textContent='Editar pregunta';form.elements.question.focus();}if(del){confirm('¿Eliminar esta pregunta?','Podés cancelar para conservarla.',()=>{const next=QuestionStore.get();next.questions=next.questions.filter(q=>q.id!==del.dataset.delete);if(save(next,'Pregunta eliminada.')){if(editing===del.dataset.delete)reset();list();}});}};
  stage.querySelector('#export-bank').onclick=()=>{const blob=new Blob([JSON.stringify(QuestionStore.get(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bibliodera-preguntas.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Copia exportada. Guardala antes de cambiar de dispositivo.');};
  stage.querySelector('#import-bank').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('El archivo supera 1 MB.');const next=QuestionStore.validate(JSON.parse(await file.text()));confirm('¿Reemplazar el banco?',`Se cargarán ${next.questions.length} preguntas y un tiempo de ${next.seconds} segundos.`,()=>{if(save(next,'Copia importada.')){reset();stage.querySelector('[name=seconds]').value=next.seconds;list();}});}catch(err){message('No se pudo importar: '+err.message);}e.target.value='';};
  if(selected==='preguntas'){
   const categoryForm=document.createElement('form');categoryForm.className='category-editor';categoryForm.innerHTML=`<h2>Categorías de la ruleta</h2><p>Podés cambiar los primeros cuatro nombres. Las preguntas conservan su categoría al renombrarla.</p><div class="category-fields">${BiblioderaContent.categories.map((c,i)=>`<label>${BiblioderaUI.categoryIcon(c)}${c.fixed?`<span>${esc(c.label)} <small>Fija</small></span>`:`<span>Categoría ${i+1}</span><input name="category${i}" aria-label="Nombre de categoría ${i+1}" value="${esc(c.label)}" maxlength="28" required>`}</label>`).join('')}</div><button class="button" type="submit">Guardar categorías</button><p role="status" class="category-status"></p>`;
   stage.querySelector('.settings-layout').after(categoryForm);
   categoryForm.onsubmit=e=>{e.preventDefault();const status=categoryForm.querySelector('.category-status');try{CategoryStore.save([0,1,2,3].map(i=>categoryForm.elements['category'+i].value));const previous=form.elements.category.value;form.elements.category.innerHTML=BiblioderaContent.categories.slice(0,4).map((c,i)=>`<option value="${i}">${esc(c.label)}</option>`).join('');form.elements.category.value=previous;list();status.textContent='Categorías guardadas.';}catch(err){status.textContent=err.message;}};
  }
  list();VideoLoop.mount(stage,selected);stage.focus({preventScroll:true});window.scrollTo(0,0);
 }
 return {render};
})();
